// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
    {
        "name": "VT_FullScreen",
        "status": false,
        "description": "Automatically starts the game in fullscreen mode and quit option.",
        "parameters": {}
    },
    {
        "name": "Zoom",
        "status": true,
        "description": "v0.6.0 Map zoom",
        "parameters": {
            "Default zoom for maps": "2.00",
            "Always free camera": "false",
            "Fix sprite black lines": "true",
            "Fix map encounter zoom": "true"
        }
    },
    {
        "name": "VT_ActorOverlay",
        "status": true,
        "description": "Displays an overlay with actor picture, HP, and MP bars.",
        "parameters": {}
    },
    {
        "name": "GALV_AutoCommonEventsMZ",
        "status": true,
        "description": "(v.1.4) Run selected common events automatically during certain parts of the game process",
        "parameters": {
            "loadFile": "0",
            "saveFile": "0",
            "mapStart": "1",
            "mapLoad": "1",
            "battleLoad": "1",
            "enterVehicle": "0",
            "exitVehicle": "0",
            "gameOver": "0",
            "timerEnd": "0"
        }
    },
    {
        "name": "AltMenuScreen",
        "status": true,
        "description": "Alternative menu screen layout.",
        "parameters": {}
    },
    {
        "name": "healthbar",
        "status": true,
        "description": "v1.0.1 - Theo Enemy HP Gauge | Visual HP gauge for the enemies",
        "parameters": {
            "option": "",
            "pos": "Bottom",
            "defeat": "false",
            "alwaysShown": "true",
            "prop": "",
            "width": "200",
            "height": "15",
            "animeDur": "45",
            "displayDur": "25",
            "border": "2",
            "segments": "1",
            "gaugecolor": "",
            "lcolorindex": "10",
            "rcolorindex": "29",
            "bcolorindex": "15",
            "aftImage": "18",
            "aftAlpha": "200"
        }
    },
    {
        "name": "float",
        "status": true,
        "description": "Adds floating movement to enemy sprites in battle, making them more dynamic.",
        "parameters": {}
    },
    {
        "name": "CustomLogo",
        "status": true,
        "description": "Shows RPG Maker and user logos at the start of the game.",
        "parameters": {
            "logo1": "",
            "logo1ImageName": "TeamTales",
            "logo1Skippable": "true",
            "logo1Coordinate": "",
            "logo1X": "448",
            "logo1Y": "28",
            "logo1Origin": "0",
            "logo1Time": "",
            "logo1FadeinFrames": "24",
            "logo1FadeoutFrames": "24",
            "logo1DurationFrames": "180",
            "logo2": "",
            "logo2ImageName": "",
            "logo2Skippable": "true",
            "logo2Coordinate": "",
            "logo2X": "408",
            "logo2Y": "312",
            "logo2Origin": "0.5",
            "logo2Time": "",
            "logo2FadeinFrames": "12",
            "logo2FadeoutFrames": "12",
            "logo2DurationFrames": "120",
            "logo3": "",
            "logo3ImageName": "",
            "logo3Skippable": "true",
            "logo3Coordinate": "",
            "logo3X": "408",
            "logo3Y": "312",
            "logo3Origin": "0.5",
            "logo3Time": "",
            "logo3FadeinFrames": "12",
            "logo3FadeoutFrames": "12",
            "logo3DurationFrames": "120",
            "allowTotalSkip": "true"
        }
    },
    {
        "name": "VT_TextPicture",
        "status": true,
        "description": "Displays text as a picture.",
        "parameters": {}
    },
    {
        "name": "VT_Battle_Sprite",
        "status": true,
        "description": "Adjusts the side-view battle sprite positions for 1080p resolution.",
        "parameters": {
            "OffsetX": "1400",
            "OffsetY": "600",
            "ScaleX": "3",
            "ScaleY": "3",
            "SpacingX": "150",
            "SpacingY": "100"
        }
    },
    {
        "name": "VT_Battle_BattleStatus",
        "status": false,
        "description": "Customizes the battle menu UI and functionality.",
        "parameters": {}
    },
    {
        "name": "VT_Battle_BattleStatus_Animation",
        "status": false,
        "description": "Customizes the battle status animation.",
        "parameters": {}
    },
    {
        "name": "VT_Map_Clock",
        "status": true,
        "description": "Custom clock plugin that displays hours and minutes on screen.",
        "parameters": {
            "clockPositionX": "1550",
            "clockPositionY": "0",
            "fontSize": "34",
            "fontColor": "#FFD700",
            "outlineColor": "#000000"
        }
    },
    {
        "name": "GoldHUD",
        "status": true,
        "description": "Displays a customizable gold counter with adjustable position, opacity, and font settings via the Plugin Manager.",
        "parameters": {
            "Window X Offset": "60",
            "Window Y Offset": "60",
            "Window Opacity": "255",
            "Font Size": "22",
            "Font Color": "#FFD700",
            "Outline Color": "#000000"
        }
    },
    {
        "name": "VT_Shader_Manager",
        "status": true,
        "description": "Manages and loads custom shaders for use in RPG Maker MZ. Version 1.0",
        "parameters": {
            "ShaderFolder": "shaders/"
        }
    },
    {
        "name": "VT_Shader_EventLight",
        "status": true,
        "description": "",
        "parameters": {}
    },
    {
        "name": "DJ_BattleStatus",
        "status": true,
        "description": "Customizes the battle status menu.",
        "parameters": {
            "hpBarColor": "rgb(255, 68, 68)",
            "mpBarColor": "rgb(0, 38, 255)",
            "tpBarColor": "rgb(0, 173, 0)",
            "hpBarColor2": "rgb(255, 68, 68)",
            "mpBarColor2": "rgb(0, 38, 255)",
            "tpBarColor2": "rgb(0, 173, 0)",
            "gaugesWidth": "256"
        }
    },
    {
        "name": "DJ_Wardrobe",
        "status": true,
        "description": "Make it possible to access wardrobe system via plugin commands.",
        "parameters": {}
    }
];
